name: Check CTRF

on:
  workflow_dispatch:
    inputs:
      threads:
        description: 'Threads'
        default: '2'
        required: false

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run integration tests
        run: ./gradlew :integration-tests:test -Dthreads=${{ github.event.inputs.threads }}

      - name: Publish CTRF Test Report
        uses: ctrf-io/github-test-reporter@v1.0.3
        with:
          report-path: 'integration-tests/build/test-results/test/ctrf-report.json'

          summary-report: true
          test-report: true
          fail-rate-report: true
          failed-folded-report: true
          previous-results-report: true
          skipped-report: true

          annotate: true
          previous-results-max: 10
          artifact-name: 'ctrf-report'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: integration-tests/build/test-results
        if: always()