name: Check CTRF

on:
  workflow_dispatch:
    inputs:
      threads:
        description: 'Threads'
        default: '2'
        required: false

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run integration tests
        run: ./gradlew :integration-tests:test -Dthreads=${{ github.event.inputs.threads }}

      - name: Run CTRF annotations
        run: npx github-actions-ctrf integration-tests/build/test-results/test/ctrf-report.json
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: integration-tests/build/test-results
        if: always()