name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build -x test

      - name: Run unit tests
        run: ./gradlew test -PexcludedTags=integration

      - name: Run CTRF annotations
        run: npx github-actions-ctrf build/test-results/test/ctrf-report.json
        if: always()