name: Listener Integration tests

on:
  workflow_dispatch:
    inputs:
      threads:
        description: 'Threads'
        default: '2'
        required: false
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      CTRF_REPORT_PATH: 'integration-tests-listener/build/test-results/ctrf-report.json'

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate report with listener
        run: |
          ./gradlew :integration-tests-listener:test \
          -Dthreads=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.threads || '2' }} \
          -Dctrf.build.name=system-build \
          -Dctrf.build.number=${{ github.run_number }} \
          -Dctrf.build.url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \
        if: always()

      - name: Publish CTRF Test Report
        uses: ctrf-io/github-test-reporter@v1.0.25
        with:
          report-path: ${{ env.CTRF_REPORT_PATH }}

          summary-report: true
          test-report: true
          fail-rate-report: true
          failed-folded-report: true
          previous-results-report: true
          skipped-report: true

          annotate: true
          previous-results-max: 10
          artifact-name: 'ctrf-report'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()

      - name: Run integration tests
        run: |
          ./gradlew :integration-ctrf-validator:test \
          -Dctrf.report.path=../${{ env.CTRF_REPORT_PATH }}
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: integration-tests-listener/build/test-results
        if: always()
